# Generated by cucumber-sinatra. (2011-06-24 23:58:54 -0700)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/url_short.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = UrlShort

class UrlShortWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  UrlShortWorld.new
end
